"use client";
import Image from "next/image"; import Link from "next/link"; import { useMemo } from "react";
import { articles, type Article } from "@/data/articles"; import { mergeBySlug } from "@/lib/cms-data"; import { usePublicContent } from "@/components/usePublicContent";
type CmsArticle = Article & { enabled?: boolean; description?: string };
function useArticles() { const content = usePublicContent(); return useMemo(() => mergeBySlug<CmsArticle>(articles, content.articles as Partial<CmsArticle>[]).filter((item) => item.enabled !== false), [content.articles]); }
function Cover({ article, sizes }: { article: CmsArticle; sizes: string }) { const src = article.coverImage || "/temporary/services/property-ai-temporary.png"; return <Image src={src} alt={article.coverImageAlt || `ภาพปก ${article.title}`} fill unoptimized={src.startsWith("http")} sizes={sizes}/>; }
export function CmsHomeArticles() { const list = useArticles(); return <div className="strip-list">{list.map((article, index) => <Link key={article.slug} href={`/articles/${article.slug}`}><article><div className="article-cover"><Cover article={article} sizes="(max-width: 620px) 100vw, 33vw"/><span>{String(index + 1).padStart(2, "0")}</span></div><div className="article-card-copy"><small>{article.category}</small><h3>{article.title}</h3><p>{article.excerpt}</p><b>อ่านบทความ →</b></div></article></Link>)}</div>; }
export function CmsArticlesListing() { const list = useArticles(); return <div className="articles-grid">{list.map((article) => <Link key={article.slug} href={`/articles/${article.slug}`}><article><div className="article-cover"><Cover article={article} sizes="(max-width: 620px) 100vw, 33vw"/></div><div className="article-card-copy"><span>{article.category}</span><h2>{article.title}</h2><p>{article.excerpt}</p><small>{article.publishedAt} · {article.readingTime}</small><b>อ่านบทความ →</b></div></article></Link>)}</div>; }
export function CmsArticleDetail({ slug }: { slug: string }) { const article = useArticles().find((item) => item.slug === slug); if (!article) return <section className="section empty-state"><h1>ไม่พบบทความ</h1><Link href="/articles">กลับไปหน้าบทความ</Link></section>; return <article className="article-page"><header><div className="article-hero-cover"><Cover article={article} sizes="100vw"/><div aria-hidden="true"/></div><div className="article-hero-copy"><Link href="/articles">← บทความทั้งหมด</Link><p className="kicker">{article.category}</p><h1>{article.title}</h1><p>{article.excerpt}</p><small>{article.publishedAt} · {article.readingTime}</small></div></header><div className="article-content">{article.paragraphs?.map((paragraph, index) => <p key={index}>{paragraph}</p>)}<div className="notice"><strong>ข้อควรทราบ</strong><p>เนื้อหานี้เป็นข้อมูลทั่วไป โปรดตรวจสอบข้อเท็จจริงและขอคำแนะนำจากผู้เชี่ยวชาญที่เกี่ยวข้องก่อนตัดสินใจ</p></div></div></article>; }
